catstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catstagram.common.urls')),
    path('accounts/', include('catstagram.accounts.urls')),
    path('cats/', include('catstagram.cats.urls')),
    path('photos/', include('catstagram.photos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catstagram/common/models.py
from django.contrib.auth import get_user_model
from django.db import models

from catstagram.photos.models import Photo

CatstagramUserModel = get_user_model()


class PhotoComment(models.Model):
    MAX_TEXT_LENGTH = 300

    text = models.CharField(
        max_length=MAX_TEXT_LENGTH,
        null=False,
        blank=False,
    )

    publication_date_and_time = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=False,
    )

    photo = models.ForeignKey(
        Photo,
        on_delete=models.RESTRICT,
        null=False,
        blank=True,
    )

    user = models.ForeignKey(
        CatstagramUserModel,
        on_delete=models.RESTRICT,
    )


class PhotoLike(models.Model):
    photo = models.ForeignKey(
        Photo,
        on_delete=models.RESTRICT,
        null=False,
        blank=True,
    )

    user = models.ForeignKey(
        CatstagramUserModel,
        on_delete=models.RESTRICT,
    )

templates/base/partials/nav.html
{% load static %}
<nav class="navbar">
    <div class="container">
        <div class="logo">
            <a href="{% url 'index' %}">
                <img width="60px" src="{% static 'images/icon.png' %}" alt="img1">
            </a>
            <a class="home" href="{% url 'index' %}">
                <i>Catstagram</i>
            </a>
        </div>
        <div class="nav-links">
            <ul class="nav-group">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'add cat' %}">
                            <i>Add Cat</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'add photo' %}">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'details user' pk=request.user.pk %}">
                            <i>Profile</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'logout user'%}">
                            <i>Sign out</i>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'login user' %}">
                            <i>Sign in</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'register user' %}">
                            <i>Sign up</i>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/base/partials/photo-item.html
{% load static %}
<div class="card">
    <div class="top">
        <div class="userDetails">
            <a href="{% url 'details user' pk=photo.user_id %}">
                <div class="profilepic">
                    <div class="profile_img">
                        <div class="image">
                            <img src="{% static 'images/person.png' %}" alt="img8">
                        </div>
                    </div>
                </div>
            </a>
            <h3>
                <a href="{% url 'details user' pk=photo.user_id %}">
                    {% if photo.user.profile.full_name %}
                        {{ photo.user.profile.full_name }}
                    {% else %}
                        {{ photo.user.email }}
                    {% endif %}

                </a>
                <br>
                {% if photo.locations %}
                    <span>{{ photo.locations }}</span>
                {% endif %}
                {% if photo.description %}
                    <p class="cat-details">{{ photo.description }}</p>
                {% endif %}
            </h3>
        </div>
    </div>
    <div class="imgBx" id="photo-{{ photo.pk }}">
        <img src="/media/{{ photo.photo }}" alt="post" class="cover">
    </div>
    <div class="bottom">
        <div class="actionBtns">
            <div class="left">
                <span class="heart">
									<a href="{% url 'like photo' photo_id=photo.pk %}">
										{% if photo.is_liked_by_user %}
                                            <svg style="color: #FFA7A6"
                                                 xmlns="http://www.w3.org/2000/svg"
                                                 width="24"
                                                 height="24"
                                                 fill="currentColor"
                                                 class="bi bi-heart-fill"
                                                 viewBox="0 0 16 16">
                                            <path fill-rule="evenodd"
                                                  d="M8 1.314C12.438-3.248 23.534 4.735
                                                  8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                                  fill=#FFA7A6>
                                            </path>
                                        </svg>
                                        {% else %}
                                            <svg aria-label="Like"
                                                 color="#262626"
                                                 fill="#FFA7A6"
                                                 height="24"
                                                 role="img"
                                                 viewBox="0 0 48 48"
                                                 width="24">
                                        <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4
                                                    11.5 0 6.8-5.9 11-11.5 16S25 41.3 24
                                                    41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3
                                                    11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3
                                                    1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9
                                                    1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9
                                                    1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1
                                                    0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3
                                                    1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3
                                                    1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2
                                                    7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6
                                                    48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                                        </path>
                                    </svg>
                                            </a>
                                            </span>
                                        {% endif %}
            </div>
        </div>
        <p class="likes">{{ photo.likes_count }} likes</p>
        {% for cat in photo.tagged_cats.all %}
            <a href="{% url 'details cat' pk=user.pk cat_slug=cat.slug %}">
                <p class="message">
                    <b>{{ cat.name }}</b>
                </p>
            </a>
        {% endfor %}
{#        <a href="{% url 'details photo' pk=photo.pk %}">#}
{#            <h4 class="details">See details...</h4>#}
{#        </a>#}
        <h5 class="postTime">{{ photo.publication_date }}</h5>
        {% for comment in photo.photocomment_set.all %}
            <div class="comments">
                <div class="top">
                    <div class="userDetails">
                        <div class="comment-data">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <!-- User Profile Image -->
                                        <img src="{% static 'images/person.png' %}" alt="img8">
                                    </div>
                                </div>
                            </div>
                            <p>
                                <a href="{% url 'details user' pk=object.pk %}">{{ object.username }} : </a>
                                {{ comment.text }}
                            </p>
                        </div>
                        <span>{{ comment.publication_date_and_time }}</span>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="addComments">
            <div class="reaction">
                <h3>
                    <i class="far fa-smile"></i>
                </h3>
            </div>
            <form method="post" action="{% url 'comment photo' photo_id=photo.pk user_id=user.pk %}">
                {{ comment_form }}
                <button type="submit">Post</button>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>